### PR TITLE
Add signature latte recipe

### PR DESCRIPTION
**Pull request by Deep130197**
This Pull Request adds a new file, 'signature_latte.txt' , to the 'recipes' folder. The file contain the recipe for our new signature latte, which will be featured in our special menu.

changes:
-Added 'recipes/signature_latte.txt' with the Signature Latte recipe.

No other files were affected.

Please review and merge the changes.

### CODE REVIEW

**Comment by Deep130197** [comment]
'cafe_branch1_menu.md' file should include a reference to the new 'signature_latte' recipe.

**Comment by Yojit2898** [comment]
'cafe_branch1_menu.md' file should include a reference to the new 'signature_latte" recipe.

**Review by Yojit2898 — COMMENTED** [review]
'cafe_branch1_menu.md' file should include a reference to the new 'signature_latte" recipe.

**Review by Yojit2898 — CHANGES_REQUESTED** [review]
'cafe_branch1_menu.md' file should include a reference to the new 'signature_latte" recipe.

**Review by Yojit2898 — APPROVED** [review]

**Pull request merged**
